blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shamsla.urls')),
    path('users/', include('users.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/users/urls.py
from django.urls import path
from django.contrib.auth import views as authViews

from . import views


urlpatterns = [
    path('register/', views.register, name="register"),
    path('login/', authViews.LoginView.as_view(template_name='users/userHandle/login.html'), name="login"),
    path('logout/', authViews.LogoutView.as_view(
        template_name='users/userHandle/logout.html'), name="logout"),
    path('profile/<user_name>/', views.profile, name="profile"),
    path('author/change/', views.userProfileChange, name="profile-change"),
    path('following/', views.following, name="following")

]

blog/users/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

from PIL import Image

# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    join_date = models.DateTimeField(default=timezone.now)
    image = models.ImageField(
        default='default/default.png', upload_to='profile_pics')

    def __str__(self):
        return self.user.username + ' Profile'

    def save(self, *args, **kwargs):

        super().save()

        img = Image.open(self.image.path)
        w, h = img.size

        # * squaring and resizing the image

        if w > 300 or h > 300 or w != h:

            if w != h:
                points = None
                if h < w:
                    diff = w - h
                    if diff == 1:
                        points = (0, 0, h, h)
                    else:
                        d0ver2 = diff/2
                        points = (d0ver2, 0, h + d0ver2, h)

                else:
                    points = (0, 0, w, w)

                img = img.crop(points)

            if w > 300 or h > 300:
                img.thumbnail((300, 300))

            img.save(self.image.path)


class FollowingUsers(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="following_user")
    followings = models.ForeignKey(
        Profile, related_name="followings", on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.followings.user.username} follows {self.user.username}'


class FollowerUsers(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="follower_user")
    followers = models.ForeignKey(
        Profile, related_name="followers", on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.followers.user.username} followed by {self.user.username}'

blog/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile

class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class UpdateUserForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']

class UpdateProfileForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ['image']

blog/users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseNotFound, JsonResponse
from django.contrib import messages
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .forms import UserRegistrationForm, UpdateProfileForm, UpdateUserForm
from json import loads as loadJson
from shamsla.custom_funcs import getLoadedJson


def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(
                request, f'Account Successfully Created For {username.title()}')

            return redirect('login')
        else:

            new_form = UserRegistrationForm()

            return render(request, 'users/userHandle/register.html', {'form': new_form, 'errors': [f"{name.title()}: {e}" for name, error in form.errors.items() for e in error]})
    else:
        form = UserRegistrationForm()
        return render(request, 'users/userHandle/register.html', {'form': form})


def profile(request, user_name):

    user = get_object_or_404(User, username=user_name)

    posts = user.post_author.all()
    posts = posts[:10] if len(posts) > 10 else posts

    followings = user.profile.followings.all().count()
    followers = user.profile.followers.all().count()

    total_posts = posts.count()

    params = {
        'pro_user': user,
        'posts': posts,
        'total_posts': total_posts,
        'followings': followings,
        'followers': followers
    }

    auth_user = request.user

    if auth_user.is_authenticated:
        params['follow_or_not'] = auth_user.profile.followings.filter(
            user=user).exists()

    return render(request, 'users/userProfile/profile.html', params)


@login_required
def userProfileChange(request):

    params = {}

    if request.method == 'POST':

        user_form = UpdateUserForm(request.POST, instance=request.user)
        profile_form = UpdateProfileForm(
            request.POST, request.FILES, instance=request.user.profile)

        if user_form.is_valid() and profile_form.is_valid():

            user_form.save()
            profile_form.save()

            messages.success(request, 'Profile Successfully Updated!')
            return redirect('profile-change')

        else:
            params['errors'] = {

                'user_errors': [f"{name.title()}: {e}" for name, error in user_form.errors.items() for e in error],
                'profile_errors': [f"{name.title()}: {e}" for name, error in profile_form.errors.items() for e in error]

            }

    user_form = UpdateUserForm(instance=request.user)
    profile_form = UpdateProfileForm(instance=request.user.profile)

    params['user_form'] = user_form
    params['profile_form'] = profile_form

    return render(request, 'users/userProfile/profile_change.html', params)


@login_required
def following(request):

    def status_404(): return JsonResponse({'status': 404})
    def status_200(): return JsonResponse({'status': 200})

    if request.method == 'POST':
        try:
            data, user_id, follow_type = getLoadedJson(
                request.body, ['uid', int], ['type', lambda t:t])
            # data = loadJson(request.body)
            # user_id = int(data['uid'])
            # # * it could be either follower/following
            # follow_type = data['type']
            print(user_id, follow_type, data)
        except:
            return status_404()

        req_user = request.user  # * profile of logged in user
        to_user = User.objects.filter(id=user_id)  # * user to follow/following

        if not to_user.exists():
            return status_404()
        else:
            to_user = to_user[0]

        # * checking that is the req_user following to_user
        to_user_check = req_user.profile.followings.filter(user=to_user)

        if follow_type == "follow" and to_user != req_user:
            if not to_user_check.exists():
                req_user.profile.followings.create(user=to_user)
                to_user.profile.followers.create(user=req_user)
                return status_200()

        elif follow_type == "unfollow" and to_user != request.user:
            # * checking that is the req_user following to_user or not

            if to_user_check.exists():
                to_user_check[0].delete()  # * deleting the req_user following
                # * deleting to_user follower[req_user]
                to_user.profile.followers.filter(user=req_user).delete()
                return status_200()

    return status_404()

blog/users/templates/users/userProfile/profile.html
{% extends 'shamsla/layout/index.html' %}

{% load static %}

{% block styles %}

<link rel="stylesheet" href="{% static 'rawstatic/css/profile.10a035b7.css' %}">
<link rel="stylesheet" href="{% static 'rawstatic/css/default/media.db65f61a.css' %}">

{% endblock styles%}

{% block title %} {{pro_user|title}} Profile {% endblock title%}

{% block content %}


<div class="wrapper border">
        <div class="inner d-flex align-items-center">

                <img class="rounded-circle mr-4" width="170" height="170" src="{{ pro_user.profile.image.url }}"
                        alt="profile-image">

                <div class="info">
                        <h6>
                                <b class="text-muted">Username . </b>
                                <span class="text-primary">@{{pro_user.username}}
                                </span>
                        </h6>
                        <h6 class="text-muted"><b>Email . </b>
                                <span>{{pro_user.email}}</span>
                        </h6>

                        <h6 class="text-muted">
                                <b>Joined .
                                </b>
                                <span>{{pro_user.profile.join_date|date:"F j, Y"}}</span>
                        </h6>
                        <div class="d-lg-none">
                                {% include 'users/userProfile/small_following.html' %}
                        </div>

                </div>
        </div>

        <div class="stats border rounded d-none d-lg-block">

                <a href="{% url 'user-posts' pro_user.username %}" class="btn btn-secondary d-block mt-3 btn-sm">
                        Followings
                </a>
                <a href="{% url 'user-posts' pro_user.username %}" class="btn btn-secondary d-block mt-3 btn-sm">
                        Followers
                </a>
                <a href="{% url 'user-posts' pro_user.username %}" class="btn btn-secondary d-block mt-3 mb-3 btn-sm">
                        See Posts
                </a>
        </div>




        {% include 'users/userProfile/stats.html' %}
</div>

{% include 'users/userProfile/u_posts.html' %}

{% endblock content%}

{% block add_script %}
<script src="{% static 'rawstatic/js/follow.1cafb80a.js' %}"></script>
<script>
        $('button.following').on('click', async (e) => {
                let follow_type = await targetFollowing(e, style_follow = [
                        ['background-color', '#007bff']
                ], style_unfollow = [
                        ['background-color', '#343a40']
                ], plus = true);

                //* to change the counting of followers stat.
                let follow_span = $('span.follower');
                let span_num = Number(follow_span.text());

                if (follow_type == 'follow') follow_span.text(span_num + 1)

                else if (follow_type = "unfollow") follow_span.text(span_num - 1)
        })
</script>

{% endblock add_script %}

blog/users/templates/users/userProfile/profile_change.html
{% extends 'shamsla/layout/index.html' %}

{% load static %}

{% block styles %}

<link rel="stylesheet" href="{% static 'users/css/change_pro.06508ae5.css' %}">

{% endblock styles %}

{% block title %} {{user.username|title}} | Profile Settings {% endblock %}

{% block content %}

<br>
<div class=" d-flex justify-content-center">
  <div class="pro-wrapper border p-5">
    <div class="pro_info d-flex flex-column justify-content-center align-items-center">

      <img class="rounded-circle" width="200" src="{{ user.profile.image.url }}" alt="profile-image">
      <br>
      <div class="info">
        <h6><b class="text-muted">Username . </b><span class="text-primary">@{{user.username}}</span></h6>
        <h6 class="text-muted"><b>Email . </b><span>{{user.email}}</span></h6>
        <h6 class="text-muted"><b>Joined . </b><span>{{user.profile.join_date|date:"F j, Y"}}</span></h6>
      </div>
    </div>

    <br>
    <br>
    <h4><b>Change Profile</b></h4>
    <br>

    {% include 'shamsla/layout/flash_messages.html' %}
    {% include 'shamsla/layout/errors_boil.html' with errors=errors.user_errors  %}
    {% include 'shamsla/layout/errors_boil.html' with errors=errors.profile_errors  %}

    <form method="POST" enctype="multipart/form-data">

      {% csrf_token %}

      {% include "shamsla/layout/user_boil.html" with label="Username" for_id="id_username" input=user_form.username %}

      {% include "shamsla/layout/user_boil.html" with label="Email" for_id="id_email" input=user_form.email %}

      {% include "shamsla/layout/user_boil.html" with label="Image" for_id="id_image" input=profile_form.image type="file" %}

      <br>
      <br>
      <button type="submit" class="btn btn-primary">Change Profile</button>

    </form>
  </div>
</div>
<br><br>

{% block add_script %}
<script>
  $('.custom-file-input').on('change', function () {
    let fileName = $(this).val().split('\\').pop();
    console.log(fileName)
    $(this).next('.custom-file-label').addClass("selected").html(fileName);
  });
</script>
{% endblock %}


{% endblock %}

blog/users/templates/users/userProfile/stats.html
{% load formsfilter %}

<div class="bt-stat d-flex align-items-center justify-content-between">
    <div class="info-stat d-flex align-items-center justify-content-between">

        <p class="text-center m-0 text-dark bt-stat-text">
            <span class="d-none d-lg-inline">Posts</span>
            <span class="d-lg-none">
                <a href="{% url 'user-posts' pro_user.username %}" class="text-dark sm-link">
                    Posts
                </a>
            </span>
            <br>
            <span class="text-muted stat-val">{{total_posts}}</span>
        </p>
        <p class="text-center m-0 text-dark bt-stat-text">
            <span class="d-none d-lg-inline">Following</span>
            <span class="d-lg-none">
                <a href="{% url 'user-posts' pro_user.username %}" class="text-dark sm-link">
                    Following
                </a>
            </span>
            <br>
            <span class="text-muted stat-val following">{{followings}}</span>
        </p>
        <p class="text-center m-0 text-dark bt-stat-text">
            <span class="d-none d-lg-inline">Followers</span>
            <span class="d-lg-none">
                <a href="{% url 'user-posts' pro_user.username %}" class="text-dark sm-link">
                    Followers
                </a>
            </span>
            <br>
            <span class="text-muted stat-val follower">{{followers}}</span>
        </p>
        <p class="text-center m-0 text-dark bt-stat-text">Likes<br><span class="text-muted stat-val">100.8K</span></p>
        <p class="text-center m-0 text-dark bt-stat-text">Comments<br><span class="text-muted stat-val">54K</span></p>

    </div>
    {% if user == pro_user %}
    <div class="action">
        <a style="font-size: 16px;" class="btn btn-primary" href="{% url 'profile-change' %}"><i class="fas fa-cog"></i>
            Edit Profile</a>
    </div>
    {% endif %}

    {% if user.is_authenticated and user != pro_user %}
    <div class="action">
        {% if user|check_following:pro_user %}
        <button style="font-size: 16px;" type="submit" class="following border-0 btn btn-dark"
            data-uid="{{pro_user.id}}" data-type="unfollow">Unfollow</button>
        {% else %}
        <button style="font-size: 16px;" type="submit" class="following border-0 btn btn-primary"
            data-uid="{{pro_user.id}}" data-type="follow">+Follow</button>
        {% endif %}
    </div>
    {% endif %}

</div>