blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shamsla.urls')),
    path('users/', include('users.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/shamsla/urls.py
from django.urls import path
from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.PostListView.as_view(), name="blog-home"),
    path('post/<int:pk>/', views.PostDetailView.as_view(), name="post-detail"),
    path('post/<int:pk>/update/', views.PostUpdateView.as_view(), name="post-update"),
    path('post/<int:pk>/delete/', views.PostDeleteView.as_view(), name="post-delete"),
    path('posts/<author>/', views.UserPostsListView.as_view(), name="user-posts"),
    path('post/new/', views.PostCreateView.as_view(), name="post-create"),
    path('post/like/', views.likePost, name="post_like"),
    path('post/comment/', views.createComment, name="post_comment"),
    path('post/comment/reply/', views.postCommentReply, name="comment_reply"),
    path('post/comment/reply/get/', views.getReplies, name="get_replies"),
    path('post/comment/get/', views.getComments, name="get_comment"),
    path('post/comment/like/', views.likeComment, name="like_comment"),
]

blog/shamsla/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="post_author")
    likes = models.ManyToManyField(User, related_name="likes", blank=True)

    def save(self, *args, **kwargs):
        self.title = self.title.title()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.pk})


class Comment(models.Model):
    post = models.ForeignKey(
        Post, related_name="post_comments", on_delete=models.CASCADE, null=True, blank=True)
    user = models.ForeignKey(
        User, related_name="comment_user", on_delete=models.CASCADE)
    body = models.TextField()
    likes = models.ManyToManyField(User, related_name="post_likes", blank=True)
    dislikes = models.ManyToManyField(
        User, related_name="post_dislikes", blank=True)
    replies = models.ForeignKey(
        "self", related_name="comment_replies", blank=True, null=True, on_delete=models.CASCADE)
    created = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ["created"]

    def __str__(self):
        try:
            return f"{self.user.username} commented on {self.post.title}"
        except:
            return f"{self.user.username} replied"


class CommentReply(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField()
    replies = models.ForeignKey("self", on_delete=models.CASCADE)

# >>> from . import models
# Traceback (most recent call last):
#   File "<console>", line 1, in <module>
# KeyError: "'__name__' not in globals"
# >>> from shamsla.models import models
# >>> from shamsla.models import Post
# >>> from django.contrib.auth.models import User
# >>> Post.objects.all()
# <QuerySet []>
# >>> User.first()
# Traceback (most recent call last):
#   File "<console>", line 1, in <module>
# AttributeError: type object 'User' has no attribute 'first'
# >>> User.objects.first()
# <User: shamsla>
# >>> user = User.objects.first()
# >>> Post(title='Post 1', content='Post 1 Content', author=user).save()
# >>> Post.objects.all()
# <QuerySet [<Post: Post 1>]>
# >>> user.post_set.create(title='Post 1', content='Post 1 Content')
# <Post: Post 1>
# >>> Post.objects.all()
# <QuerySet [<Post: Post 1>, <Post: Post 1>]>
# >>>

blog/users/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

from PIL import Image

# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    join_date = models.DateTimeField(default=timezone.now)
    image = models.ImageField(
        default='default/default.png', upload_to='profile_pics')

    def __str__(self):
        return self.user.username + ' Profile'

    def save(self, *args, **kwargs):

        super().save()

        img = Image.open(self.image.path)
        w, h = img.size

        # * squaring and resizing the image

        if w > 300 or h > 300 or w != h:

            if w != h:
                points = None
                if h < w:
                    diff = w - h
                    if diff == 1:
                        points = (0, 0, h, h)
                    else:
                        d0ver2 = diff/2
                        points = (d0ver2, 0, h + d0ver2, h)

                else:
                    points = (0, 0, w, w)

                img = img.crop(points)

            if w > 300 or h > 300:
                img.thumbnail((300, 300))

            img.save(self.image.path)


class FollowingUsers(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="following_user")
    followings = models.ForeignKey(
        Profile, related_name="followings", on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.followings.user.username} follows {self.user.username}'


class FollowerUsers(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="follower_user")
    followers = models.ForeignKey(
        Profile, related_name="followers", on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.followers.user.username} followed by {self.user.username}'

blog/shamsla/forms.py
from django import forms
from .models import Post

class PostCreateForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['title', 'content']

blog/shamsla/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseBadRequest, JsonResponse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from .models import Post, Comment
from django.contrib.auth.models import User
from .forms import PostCreateForm
from json import loads as loadJson
from .custom_funcs import getCommentTime, getLoadedJson, getRefinedCmts, getBetterReplies
from django.core.paginator import Paginator
import time
from django.views.decorators.csrf import csrf_exempt


class PostListView(ListView):
    model = Post
    context_object_name = 'posts'
    template_name = 'shamsla/home/home.html'
    ordering = ['date_posted']
    paginate_by = 10


class PostDetailView(DetailView):
    model = Post
    context_object_name = 'post'
    template_name = 'shamsla/postDetail/post_detail.html'

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)

    #     post = context['object']  # * getting post object

    #     def cmts(obj=post.post_comments.all()): return [{'name': cmt.user.username, 'img': cmt.user.profile.image.url, 'c': cmt.body, 't': getCommentTime(
    #         cmt.created), 'replies': cmts(cmt.comment_replies.all())} for cmt in obj]

    #     context['comments'] = cmts

    #     return context


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'content']
    template_name = "shamsla/postCreate/post_create.html"

    def form_valid(self, form):
        form.instance.author = self.request.user

        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    context_object_name = "post"
    template_name = "shamsla/postUpdate/post_update.html"
    fields = ['title', 'content']

    def form_valid(self, form):
        form.instance.author = self.request.user

        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()

        if post.author == self.request.user:
            return True
        return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    context_object_name = "post"
    template_name = "shamsla/postDelete/post_delete.html"
    success_url = "/"

    def test_func(self):
        post = self.get_object()

        if post.author == self.request.user:
            return True
        return False


class UserPostsListView(ListView):
    model = Post
    context_object_name = "posts"
    template_name = "shamsla/userPosts/user_posts.html"
    ordering = ["date_posted"]
    paginate_by = 10

    def get_queryset(self):
        q_set = super(UserPostsListView, self).get_queryset()

        author_name = self.request.path.split('/')[-2]
        author = get_object_or_404(User, username=author_name)

        # filtering only the users posts
        q_set = q_set.filter(author=author)
        return q_set


@login_required
def likePost(request):

    def status_404(): return JsonResponse({'status': 404})
    def status_200(): return JsonResponse({'status': 200})

    if request.method == 'POST':

        try:
            req_body, post_id = getLoadedJson(request.body, ['pid', int])
            # post_id = int(loadJson(request.body)['pid'])
        except:
            # if pid not exists or pid is not a number
            return status_404()

        user = request.user
        # if post not found
        post = Post.objects.filter(id=post_id)
        if not post.exists():
            return status_404()
        else:
            post = post[0]

        if post.likes.filter(pk=user.pk).exists():
            post.likes.remove(user)
        else:
            post.likes.add(user)

        return status_200()

    # if request is a /GET request
    return status_404()


@login_required
def createComment(request):

    def status_404(): return JsonResponse({'status': 404})
    def status_200(comment_id): return JsonResponse(
        {'status': 200, 'id': comment_id})

    if request.method == "POST":
        try:
            req_data, comment_text, post_id = getLoadedJson(
                request.body, ['body', lambda t:t], ['pid', int])

            comment_text = comment_text.strip()
            if len(comment_text) < 1:
                raise Exception()

            post = Post.objects.filter(id=post_id)
            user = User.objects.filter(username=request.user.username)

            if not post.exists() or not user.exists():
                return status_404()

            else:
                post = post[0]
                user = user[0]

            cmt = Comment.objects.create(
                post=post, user=user, body=comment_text)

            return status_200(cmt.id)

        except:
            return status_404()

    # if request is a /GET request
    return status_404()


@csrf_exempt
def getComments(request):
    def status_404(): return JsonResponse({'status': 404})
    def status_200(comments, has_next): return JsonResponse(
        {'status': 200, 'cmts': comments, 'hnext': has_next})

    if request.method == "POST":
        try:
            req_body, page_n, pid = getLoadedJson(
                request.body, ['page', int], ['pid', int])

            post = Post.objects.filter(id=pid)[0]
            cmts_list = post.post_comments.all()

            paginator = Paginator(cmts_list, 8)
            cmts = paginator.page(page_n)
            if request.user.is_authenticated:
                cmts_list = getRefinedCmts(cmts.object_list, request.user)
            else:
                cmts_list = getRefinedCmts(cmts.object_list)

            return status_200(cmts_list, has_next=cmts.has_next())

        except Exception as exp:
            print(exp)

    return status_404()


@csrf_exempt
def getReplies(request):
    def status_404(): return JsonResponse({'status': 404})
    def status_200(replies, has_next): return JsonResponse(
        {'status': 200, 'reps': replies, 'hnext': has_next})

    if request.method == "POST":
        try:
            req_body, comment_id, page_num = getLoadedJson(
                request.body, ['cid', int], ['pnum', int])

            comment = Comment.objects.filter(id=comment_id)

            if not comment.exists():
                return status_404()
            else:
                comment = comment[0]
            if request.user.is_authenticated:
                replies = getBetterReplies(getRefinedCmts(
                    comment.comment_replies.all(), request.user, reps_length=False, get_replies=True))
            else:
                replies = getBetterReplies(getRefinedCmts(
                    comment.comment_replies.all(), reps_length=False, get_replies=True))

            paginator = Paginator(replies, 8)
            reps_page = paginator.page(page_num)

            return status_200(reps_page.object_list, has_next=reps_page.has_next())

        except:
            pass

    return status_404()


@login_required
def postCommentReply(request):

    def status_404(): return JsonResponse({'status': 404})
    def status_200(comment_id): return JsonResponse(
        {'status': 200, 'id': comment_id})

    if request.method == "POST":
        try:
            req_body, comment_id, reply_text = getLoadedJson(
                request.body, ['cid', int], ['body', lambda t:t])

            comment = Comment.objects.filter(id=comment_id)
            user = User.objects.filter(username=request.user.username)

            if not comment.exists() or not user.exists():
                return status_404()
            else:
                comment = comment[0]
                user = user[0]

            reply = comment.comment_replies.create(user=user, body=reply_text)
            return status_200(reply.id)

        except:
            pass
    return status_404()


@login_required
def likeComment(request):
    def status_404(): return JsonResponse({'status': 404})
    def status_200(): return JsonResponse({'status': 200})

    if request.method == 'POST':
        req_body, comment_id, like_action, like_type = getLoadedJson(request.body, ['cid', int], [
            'action', int, lambda x: x if x in (0, 1) else None], ['type', int, lambda x: x if x in (0, 1) else None])

        # * like_type could 0|1 -- 0 -> dislike & 1 -> like
        # * like_action could 0|1 -- 0 -> remove & 1 -> add

        user = request.user
        comment = Comment.objects.filter(id=comment_id)

        if not comment.exists():
            return status_404()
        else:
            comment = comment[0]

        if like_type == 1:
            if comment.dislikes.filter(pk=user.pk).exists():
                comment.dislikes.remove(user)
        else:
            if comment.likes.filter(pk=user.pk).exists():
                comment.likes.remove(user)

        like_type = comment.likes if like_type == 1 else comment.dislikes
        like_action = like_type.add if like_action == 1 else like_type.remove

        like_action(user)

        return status_200()

    return status_404()

blog/shamsla/templates/shamsla/layout/errors_boil.html
{% for error in errors %}

    <div class="alert alert-{% if tags == True %}{{ error.tags }}{% else %}danger{% endif %}" role="alert">
        <p class="m-0">{{ error }}</p>
    </div>

{% endfor %}

blog/shamsla/templates/shamsla/layout/erros_boil.html
{% for error in errors %}

<div class="alert alert-danger" role="alert">
    <p>{{ error }}</p>
</div>

{% endfor %}

blog/shamsla/templates/shamsla/layout/flash_messages.html
{% if messages %}

{% include 'shamsla/layout/errors_boil.html' with errors=messages tags=True %}

{% endif %}

blog/shamsla/templates/shamsla/layout/ham.html
<svg height="24" class="ham" viewBox="0 0 12 16" version="1.1" width="18" aria-hidden="true">
    <path fill-rule="evenodd"
        d="M11.41 9H.59C0 9 0 8.59 0 8c0-.59 0-1 .59-1H11.4c.59 0 .59.41.59 1 0 .59 0 1-.59 1h.01zm0-4H.59C0 5 0 4.59 0 4c0-.59 0-1 .59-1H11.4c.59 0 .59.41.59 1 0 .59 0 1-.59 1h.01zM.59 11H11.4c.59 0 .59.41.59 1 0 .59 0 1-.59 1H.59C0 13 0 12.59 0 12c0-.59 0-1 .59-1z">
    </path>
</svg>

blog/shamsla/templates/shamsla/layout/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="{% static 'rawstatic/css/default/bt.78f2f00a.css' %}">
  <link rel="stylesheet" href="{% static 'rawstatic/css/default/commons.ede87e1e.css' %}">
  {% comment %} <script src="{% static 'temp/fa.js' %}"></script> {% endcomment %}

  <link rel="icon" href="{% static 'shamsla/images/fav.PNG' %}" type="image/gif">

  {% block styles %}{% endblock %}

  <title>{% block title %}{% endblock %}</title>
</head>

<body>

  {% include 'shamsla/layout/modal.html'%}
  {% include 'shamsla/layout/nav.html'%}


  <main class="container">
    {% block content %}{% endblock %}
  </main>
</body>

<script src="{% static 'temp/jq.js' %}"></script>
<script src="{% static 'temp/pp.js' %}"></script>
<script src="{% static 'temp/bt.js' %}"></script>
<script>
  const g$spin_code = `{% include 'shamsla/layout/sm_loader.html' %}`;
</script>
<script src="{% static 'rawstatic/js/default/main.3231f3c1.js' %}"></script>
{% block add_script %}{% endblock add_script%}

</html>

blog/shamsla/templates/shamsla/layout/modal.html
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Are You Sure ?</h5>
          <button style="outline: none;" type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          Next Time You Will Have To Login Again.
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-sm btn-secondary" data-dismiss="modal">Cancel</button>
          <a type="button" href="{% url 'logout' %}" class="btn btn-sm btn-primary">Logout</a>
        </div>
      </div>
    </div>
  </div>

blog/shamsla/templates/shamsla/layout/nav.html
{% load static %}

<header>
    <div class="fixed-top nav-wrap">
        <nav class="container navbar navbar-expand-lg navbar-dark pr-4 pl-4 nav-fill w-100">
            <a class="navbar-brand font-weight-bold mr-5" href="/"><img src="{% static 'shamsla/images/mainlogo.PNG' %}"
                    alt="shams la logo"></a>
            <form method="POST" class="d-flex justify-content-center form-group w-50 m-0">
                <input type="text" class=" form-control" placeholder="Search ...">
            </form>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span>
                    {% include 'shamsla/layout/ham.html' %}
                </span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">


                <ul class="navbar-nav ml-auto d-flex align-items-center">

                    <li class="nav-item mr-1">
                        <a class="nav-link" href="/">Home</a>
                    </li>

                    <li class="nav-item mr-1">
                        <a class="nav-link" href="{% url 'post-create' %}">New Post</a>
                    </li>

                    {% if user.is_authenticated %}

                    <li class="nav-item d-lg-none">
                        <a class="nav-link" href="{% url 'profile' user.username%}">Profile</a>
                    </li>
                    <li class="nav-item d-lg-none">
                        <a class="nav-link" href="{% url 'user-posts' user.username%}">Posts</a>
                    </li>
                    <li class="nav-item d-lg-none">
                        <a style="cursor: pointer;" class="nav-link" data-toggle="modal"
                            data-target="#exampleModal">Sign Out</a>
                    </li>


                    <li class="nav-item d-none d-lg-block">

                        <div class="dropdown nav-link">
                            <a class="main-drop d-flex align-items-center dropdown-toggle"
                                href="{% url 'profile' user.username %}" id="dropdownMenuButton" data-toggle="dropdown"
                                aria-haspopup="true" aria-expanded="false">
                                <img class="rounded profile-img" width="10" src="{{user.profile.image.url}}" alt="user">

                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item" href="{% url 'profile' user.username %}">Your Profile</a>
                                <a class="dropdown-item" href="{% url 'user-posts' user.username %}">Your Posts</a>
                                <a class="dropdown-item" href="{% url 'user-posts' user.username %}">Notifications</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'profile-change' %}">Edit Profile</a>
                                <a style="cursor: pointer;" class="dropdown-item" data-toggle="modal"
                                    data-target="#exampleModal">Sign Out</a>
                            </div>
                        </div>

                    </li>

                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Sign In</a>
                    </li>
                    <li class="nav-item">
                        <a class="btn btn-light nav-link" href="{% url 'register' %}">Sign Up</a>
                    </li>

                    {% endif %}

                </ul>
            </div>
        </nav>
    </div>
</header>

blog/shamsla/templates/shamsla/layout/pagination_boil.html
<br>
{% if is_paginated %}
<nav aria-label="...">
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}

        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}"><i class="fas fa-arrow-left"></i></a>
        </li>

        {% if page_obj.number > 3 %}

        <li class="page-item"><a class="page-link" href="?page=1">1</a></li>

        <li class="page-item disabled"><a style="color: #007bff;" class="page-link" href="#">...</a></li>

        {% endif%}

        {% else %}

        <li class="page-item disabled">
            <a class="page-link" href="#"><i class="fas fa-arrow-left"></i></a>
        </li>

        {% endif%}

        {% for num in page_obj.paginator.page_range %}

        {% if page_obj.number == num %}

        <li class="page-item active">
            <a class="page-link" href="?page={{ num }}">{{num}}<span class="sr-only">(current)</span></a>
        </li>

        {% elif num > page_obj.number|add:"-3" and num < page_obj.number|add:"3" %}

        <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>

        {% endif %}

        {% endfor %}

        {% if page_obj.has_next %}

        {% if page_obj.number < page_obj.paginator.num_pages|add:"-2" %}

        <li class="page-item disabled"><a style="color: #007bff;" class="page-link" href="#">...</a></li>

        <li class="page-item"><a class="page-link"
                href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a></li>

        {% endif%}

        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}"><i class="fas fa-arrow-right"></i></a>
        </li>

        {% else %}

        <li class="page-item disabled">
            <a class="page-link" href="#"><i class="fas fa-arrow-right"></i></a>
        </li>

        {% endif%}

    </ul>
</nav>
{% endif %}


<br>
<br>
<br><br>
<br><br>

blog/shamsla/templates/shamsla/layout/post_form_boil.html
{% load formsfilter %}

<div class="form-group">
    <label for="id_title">Title</label>
    {{form.title|add_attr:"class,form-control post-title;;placeholder,Type here ..."}}
</div>
<div class="form-group">
    <label for="id_content">Desciption</label>
    {{form.content|add_attr:"class,form-control post-cont;;placeholder,Type here ..."}}
</div>

blog/shamsla/templates/shamsla/layout/posts_following.html
{% load formsfilter %}

{% if user.is_authenticated and user != post.author %}
<span>
    <i class="text-muted fas fa-circle sm-dot"></i>
</span>
{% if user|check_following:post.author %}
<span>
    <form action="/users/unfollow/" method="POST">
        {% csrf_token %}
        <input type="hidden" name="uid" value="{{post.author.id}}">
        <button type="submit" class="btn btn-link btn-sm p-0">Unfollow</button>
    </form>
</span>

{% else %}
<span>
    <form action="/users/follow/" method="POST">
        {% csrf_token %}
        <input type="hidden" name="uid" value="{{post.author.id}}">
        <button type="submit" class="btn btn-link btn-sm p-0">Follow</button>
    </form>
</span>
{% endif %}
{% endif %}

blog/shamsla/templates/shamsla/layout/sm_loader.html
<div class="spinner-border spinner-border-sm text-secondary" role="status">
</div>

blog/shamsla/templates/shamsla/layout/user_boil.html
{% load formsfilter %}



{% if type == "file" %}
<label>Image</label>
<div class="custom-file">
    <input type="file" name="image" accept="image/*" class="custom-file-input" id="id_image">
    <label class="custom-file-label" for="id_image">Choose file...</label>
</div>

{% else %}
<div class="form-group">
    <label for="{{ for_id }}">{{label}}</label>
    {{input|add_attr:"class,form-control post-title"}}
</div>
{% endif %}